title: JI Sugar Ranking
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://sugaryesplz666.github.io/sugar

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/sugaryesplz666/sugar
